site_name: FourBoot Select Picker
site_description: Bootstrap-select is a jQuery plugin that utilizes Bootstrap's dropdown.js to style and bring additional functionality to standard select elements.
repo_url: https://github.com/IbraheemAlnabriss/four-boot
theme: 
    name: material
extra_css: [
            'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css',
            'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css',
            'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css',
            'css/JQuery.four-boot.css'
            ]
extra_javascript: [ 
            'https://code.jquery.com/jquery-3.3.1.slim.min.js',
            'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js',
            'https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js',
            'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js',
            'js/JQuery.four-boot.js',
            'js/custom.js']
extra:
    version: v1.0 beta